#!/bin/bash

echo "Creating document!"
touch sidecar.txt
echo "Created sidecar.txt"
echo "Adding header info"
echo -e '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' >> sidecar.txt
echo -e "<directory>\n <item_list>" >> sidecar.txt

file=$1
OLDIFS=$IFS
IFS=' '
counter=1
while read f1 f2 f3;do  
	echo -e "  <item>\n   <fn>$f1</fn>\n   <ln>$f2</ln>\n   <ct>$f3</ct>" >> sidecar.txt
	echo -e "   <sd>$counter</sd>\n   <bw>1</bw>" >> sidecar.txt
	echo -e "  </item>" >> sidecar.txt
	echo User Added!
	counter=$((counter+1))
done < "$file"
IFS=$OLDIFS

echo -e " </item_list>\n</directory>" >> sidecar.txt
